### ISSUE TITLE
极速版分享报错

### ISSUE THREAD

**Issue by hejun041** [yml2213/javascript#13]
TypeError: Cannot read properties of undefined (reading 'result')
    at do_Share (/ql/scripts/raw_ksjsb_ksjsb.js:267:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/ql/scripts/raw_ksjsb_ksjsb.js:96:9)
    at async /ql/scripts/raw_ksjsb_ksjsb.js:69:9

**Comment by yml2213** [comment]
看脚本说明   没有debug 一律不知道
