### ISSUE TITLE
ksjsb报错

### ISSUE THREAD

**Issue by Hanze-Li** [yml2213/javascript#14]
debug=1下，【debug】===============这是 用户信息 返回data==============
{"result":10022,"error_url":null,"trace_id":653458412330034791,"error_msg":"设备命中无补贴模式","host-name":"bjfk-rs15722.yz02"}
======
{
  result: 10022,
  error_url: null,
  trace_id: 653458412330034800,
  error_msg: '设备命中无补贴模式',
  'host-name': 'bjfk-rs15722.yz02'
}

 用户信息: 失败 ❌ 了呢,原因未知！  [object Object] 

❗️快手极速版, 错误!
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at user_info (/ql/data/scripts/raw_ksjsb_ksjsb.js:130:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/ql/data/scripts/raw_ksjsb_ksjsb.js:81:5)
    at async /ql/data/scripts/raw_ksjsb_ksjsb.js:69:9

🔔快手极速版, 结束! 🕛 8.102 秒

**Comment by yml2213** [comment]
没见过了  不知道为啥
