### ISSUE TITLE
咸鱼要躺平  脚本运行报错

### ISSUE THREAD

**Issue by jiemo9527** [yml2213/javascript#7]
咸鱼要躺平 line：237   ${result.data.withList[0].time} undefined ，time获取不到
使用旧版本无提现，  正常

报错后脚本终止运行

`TypeError: Cannot read properties of undefined (reading 'time')
    at Existing_credits (/ql/data/scripts/jiemo9527_ql_wool/xyytp.js:234:84)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/ql/data/scripts/jiemo9527_ql_wool/xyytp.js:94:2)
    at async /ql/data/scripts/jiemo9527_ql_wool/xyytp.js:70:3`

**Comment by jiemo9527** [comment]
√
